// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUiJK-lz1wdFf4xOyhOC4ATmTJUIt-alo',
    appId: '1:616002363932:web:7b7f415dfe48df17b535d9',
    messagingSenderId: '616002363932',
    projectId: 'whats-app-1584a',
    authDomain: 'whats-app-1584a.firebaseapp.com',
    storageBucket: 'whats-app-1584a.firebasestorage.app',
    measurementId: 'G-VK913QHNSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rEU-MRIyNrx8__8mjT6wxbQ0LexXnBQ',
    appId: '1:616002363932:android:0063d27ee0c7dbaeb535d9',
    messagingSenderId: '616002363932',
    projectId: 'whats-app-1584a',
    storageBucket: 'whats-app-1584a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZIRaNRlVpyS237sPzkYrNgurATeFiYWI',
    appId: '1:616002363932:ios:daa7980d66b1134ab535d9',
    messagingSenderId: '616002363932',
    projectId: 'whats-app-1584a',
    storageBucket: 'whats-app-1584a.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZIRaNRlVpyS237sPzkYrNgurATeFiYWI',
    appId: '1:616002363932:ios:daa7980d66b1134ab535d9',
    messagingSenderId: '616002363932',
    projectId: 'whats-app-1584a',
    storageBucket: 'whats-app-1584a.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUiJK-lz1wdFf4xOyhOC4ATmTJUIt-alo',
    appId: '1:616002363932:web:97d074cd506663b9b535d9',
    messagingSenderId: '616002363932',
    projectId: 'whats-app-1584a',
    authDomain: 'whats-app-1584a.firebaseapp.com',
    storageBucket: 'whats-app-1584a.firebasestorage.app',
    measurementId: 'G-BB5JGQC300',
  );
}
